import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { sans } from "@/lib/font";

export const metadata: Metadata = {
  title: "Green Algeria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased", sans.variable)}>{children}</body>
    </html>
  );
}
